export const PERMISSIONS = {
  SUPPORT: 'SUPPORT',

  USERS: {
    VIEW: 'USERS_CONSULT',
    CREATE: 'USERS_CREATE',
    DELETE: 'USERS_DELETE',
    CHANGE: 'USERS_CHANGE',
    ACTIVE_OR_INACTIVE: 'USERS_ACTIVE_OR_INACTIVE',
  },

  GROUPS: {
    VIEW: 'GROUPS_CONSULT',
    CREATE: 'GROUPS_CREATE',
    DELETE: 'GROUPS_DELETE',
    CHANGE: 'GROUPS_CHANGE',
    MANAGE_USERS: 'GROUPS_MANAGEMENT_USER',
    ACTIVE_OR_INACTIVE: 'GROUPS_ACTIVE_OR_INACTIVE',
    MANAGE_PERMISSIONS: 'GROUPS_MANAGEMENT_PERMISSION',
  },

  SETTINGS: {
    EMAIL_VIEW: 'EMAIL_SETTINGS_CONSULT',
    EMAIL_CHANGE: 'EMAIL_SETTINGS_PROCESS',
    EMAIL_LOG_VIEW: 'EMAIL_LOG_CONSULT',
    BACKUP_PROCESS: 'BACKUP_PROCESS',
  },
} as const;

type ValueOf<T> = T[keyof T];
type DeepValueOf<T> = T extends object ? DeepValueOf<ValueOf<T>> : T;

export type Permission = DeepValueOf<typeof PERMISSIONS>;
